
<main>
    <!-- CAROUSEL -->
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo $this->baseUrl('uploads/index-slides/devojcica.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
            <div class="item">
                <img src="<?php echo $this->baseUrl('uploads/index-slides/blonde.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
            <div class="item">
                <img src="<?php echo $this->baseUrl('front/img/main-img.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    
    <!-- ======== @Region: #content ======== -->

        <!-- SECTION 8 "shipping" -->
    <section class="shipping">
        <div class="container">
            <div class="row">
                <span>Naše usluge</span> 
                <small><a href="<?php echo $this->sitemapPageUrl($this->servicesSitemapPage['id']);?>">Vidi sve</a></small>
                <?php
                foreach ($this->services as $service) {
                        ?>
                
                <li class="col-md-3">
                            <h3 class="title">  
                                <i class="<?php echo $this->escape($service['icon']); ?> icon-small icon-inverse-80 _icon-circle"></i>
                                <?php echo $this->escape($service['title']); ?>
                            </h3>
                            <p><?php echo $this->escape($service['description']); ?></p>
                        </li>
                
                <?php
                    }
                ?>
            </div>
        </div>
    </section>
      
    
    
</main>