<?php
$photos = $this->photos;
$photoGallery = $this->photoGallery;
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);
$this->headLink()->appendStylesheet($this->baseUrl('/front/blueimp/css/bootstrap-image-gallery.min.css'));
?>

<main>
            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <li>
                            <a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                        </li>
                    </ul>
                </div>
            </section>
<div id="highlighted">
    <div class="container">
        <div class="header">
            <h2 class="page-title">
                <span><?php echo $this->escape($sitemapPage['title']); ?></span>
            </h2>
            <a href="<?php echo $this->sitemapPageUrl($sitemapPage['id']); ?>" class="btn btn-xs btn-default back-link"><i class="fa fa-arrow-left"></i> Back to all photo galleries</a>
        </div>
    </div>
</div>
<div id="content">
                
    <div class="container portfolio">
        <div class="row">
            <?php foreach ($photos as $index=>$photo) { ?>
                 <div class="col-lg-3 col-sm-4 col-xs-6"><a title="<?php echo $this->escape($photo['title']); ?>"><img class="thumbnail img-responsive" src="<?php echo $this->photoUrl($photo); ?>"></a></div>
             <?php } ?>
           <hr>
         <hr>
       </div>
    </div>
</div>
<div tabindex="-1" class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">
      <div class="modal-content">
            <div class="modal-body">
            </div>
       </div>
      </div>
    </div>
     </main>
<?php $this->inlineScript()->captureStart();?>
$(document).ready(function() {
$('.thumbnail').click(function(){
      $('.modal-body').empty();
  	var title = $(this).parent('a').attr("title");
  	$('.modal-title').html(title);
  	$($(this).parents('div').html()).appendTo('.modal-body');
  	$('#myModal').modal({show:true});
});
});
<?php $this->inlineScript()->captureEnd();?>
<?php $this->headStyle()->captureStart();?>
.modal-dialog {width:600px;}
.thumbnail {margin-bottom:6px;}
<?php $this->headStyle()->captureEnd();?>