<?php
$photos = $this->photos;
$photoGallery = $this->photoGallery;
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);
?>

<main>
            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <li>
                            <a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                        </li>
                    </ul>
                </div>
            </section>
<div id="highlighted">
    <div class="container">
        <div class="header">
            <h2 class="page-title">
                <span><?php echo $this->escape($sitemapPage['title']); ?></span>
            </h2>
            <a href="<?php echo $this->sitemapPageUrl($sitemapPage['id']); ?>" class="btn btn-xs btn-default back-link"><i class="fa fa-arrow-left"></i> Back to all photo galleries</a>
        </div>
    </div>
</div>
<div id="content">
    <div class="container portfolio">
        <!--Portfolio feature item-->
        
        <div class="row">
            
                <div class="col-md-5 project-photos">
                    <!-- Slider for project pictures -->
                    
                    <div id="photo-gallery-slider-id" class="carousel slide">
                        
                        <div class="carousel-inner">
                            <?php foreach ($photos as $index=>$photo) { ?>
                              
                            <div class="item <?php echo $index == 0 ? 'active' : '';?>">
                                <img src="<?php echo $this->photoUrl($photo); ?>" alt="<?php echo $this->escape($photo['title']); ?>" />
                                
                            </div>
                            <?php } ?>
                        </div>
                         
                        <a class="left carousel-control" href="#photo-gallery-slider-id" data-slide="prev">&lsaquo;</a> <a class="right carousel-control" href="#photo-gallery-slider-id" data-slide="next">&rsaquo;</a> 

                    </div>
                   
            </div>
             
            <div class="col-md-7 sidebar sidebar-center">
                <!-- quick details -->
                <div class="block">
                    <h3 class="block-title">
                        <span><?php echo $this->escape($photoGallery['title']); ?></span>
                    </h3>
                    <div class="block">
                        <p><?php echo $this->escape($photoGallery['description']); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
                 </main>