<?php
$photoGalleries = $this->photoGalleries;
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);
?>

<main>
            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <ul>
                            <a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                        </ul>
                    </ul>
                </div>
            </section>
        <div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span><?php echo $this->escape($sitemapPage['title']); ?></span>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
                   
			<div class="container portfolio">
				<!--Portfolio items-->
				<li class="thumbnails row block projects" id="quicksand">
                                     <?php foreach ($photoGalleries as $photoGallery) { ?>
					<ul class="col-md-4 print" data-id="1" data-type="print">
						<div class="">
							<div class="project">
								<a class="lnk-polaroid" href="<?php echo $this->photoGalleryUrl($photoGallery); ?>">
									<img src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>" alt="<?php echo $this->escape($photoGallery['title']); ?>" class="img-polaroid img-responsive" />
								</a>
								<h3 class="title">
									<a href="<?php echo $this->photoGalleryUrl($photoGallery); ?>"><?php echo $this->escape($photoGallery['title']); ?></a>
								</h3>
								<p class="muted"><?php echo $this->escape($photoGallery['description']); ?></p>
							</div>
						</div>
					</ul>
                                         <?php } ?>
					
				</ul>
			</div>
                      
</div>
                 </main>