<?php
$this->headTitle('Services');
?>

<main>
    <!-- SECTION 8 "shipping" -->
    <section class="shipping">
        <div class="container">
            <div class="row">
                <?php
                foreach ($this->services as $service) {
                        ?>
                
                <li class="col-md-4">
                            <h3 class="title">  
                                <i class="<?php echo $this->escape($service['icon']); ?> icon-small icon-inverse-80 _icon-circle"></i>
                                <?php echo $this->escape($service['title']); ?>
                            </h3>
                            <p><?php echo $this->escape($service['description']); ?></p>
                        </li>
                
                <?php
                    }
                ?>
            </div>
        </div>
    </section>
</main>
