<?php
$this->headTitle('Usluge');

?>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script><img src="cinqueterre.jpg" class="img-circle" alt="Cinque Terre" width="304" height="236"> 
  
  
  
<main>
    
    <?php echo $this->topPhoto(); ?>
    
        <div class="gridView">
            <h3 class="text-uppercase text-center"><?php echo $this->sitemapPage['title'];?></h3>
        </div>
    </section>
    
    <!-- CAROUSEL -->
<!--    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
         Indicators 
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

         Wrapper for slides 
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="<?php echo $this->baseUrl('uploads/index-slides/devojcica.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
            <div class="item">
                <img src="<?php echo $this->baseUrl('uploads/index-slides/blonde.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
            <div class="item">
                <img src="<?php echo $this->baseUrl('front/img/main-img.jpg');?>" alt="" class="img-responsive"/>
                <div class="carousel-caption">
                    
                </div>
            </div>
        </div>

         Controls 
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>-->

    <!-- SECTION 8 "shipping" -->
    <section class="shipping">
        <div class="container">
            <div class="row">
                <?php
                foreach ($this->services as $service) {
                        ?>
                
                <ol class="col-md-4">
                            <h3 class="title">  
                                
                                 
                                
                                <img src="<?= $this->frontServiceImgUrl($service);?>" class="img-circle" alt="Cinque Terre" width="304" height="236"/>
                                <i class=" icon-small icon-inverse-80 icon-circle"></i>
                                <?php echo $this->escape($service['service_name']); ?>
                            </h3>
                            <p><?php echo $this->escape($service['resume']); ?></p>
                        </ol>
                
                <?php
                    }
                ?>
            </div>
        </div>
    </section>
</main>
