<main>

            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="img/hot-stone.jpg" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    <h3 class="text-uppercase text-center">ABOUT US</h3>
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <li>
                            <a>Home</a>
                        </li>
                        <li>
                            <a> Shop</a>
                        </li>
                        <li>Grid View</li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 2 -->
            <section class="popular">
                <h4 class="text-uppercase text-center">about us</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 3 " -->
            <section class="ourCompany">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <article>
                                <h4 class="text-uppercase">who we are?</h4> 
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing 
                                    elit, sed do eiusmod tempor incididunt ut labore et 
                                    dolore magna aliqua. Ut enim ad minim veniam, quis 
                                    nostrud exercitation ullamco laboris nisi ut aliquip 
                                    ex ea commodo consequat enim ad minim veniam, 
                                    quis nostrud exercita.
                                </p>
                                <p>
                                    Excepteur sint occaecat cupidatat non proident, 
                                    sunt in culpa qui officia deserunt mollit anim id 
                                    est laborum. Sed ut perspiciatis unde omnis iste 
                                    natus error sit voluptatem accusantium 
                                </p>
                                <p>FOLLOW US:</p>
                                <ul class="list-inline list-unstyled">
                                    <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                    <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                    <li><a href="#"><span class="fa fa-pinterest-p"></span></a></li>
                                    <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                </ul>
                            </article>
                        </div>
                        <div class="col-md-6">
                            <article class="clearfix">
                                <figure>
                                    <img src="img/shop.png" alt="" class="img-responsive center-block"/>
                                </figure>
                            </article>
                        </div>
                    </div>
                </div>
            </section>

            <!-- SECTION 4 " -->
            <section class="popular">
                <h4 class="text-uppercase text-center">meet our team</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 5 " -->
            <section class="ourTeam">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <article class="singleMember clearfix">
                                <figure>
                                    <img src="img/team1.png" alt="" class="img-responsive center-block"/>

                                    <div class="teamMember text-center">
                                        <a href="#"><h4 class="text-uppercase">SARA BROWN</h4></a>
                                        <h3>MANAGER</h3>
                                        <p>
                                            Lorem ipsum dolor sit amet, consectetuer adipiscing 
                                            elit, sed diam my nibh euismod tincidunt
                                        </p>
                                        <ul class="list-inline list-unstyled">
                                            <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                            <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                            <li><a href="#"><span class="fa fa-pinterest-p"></span></a></li>
                                            <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                        </ul>
                                    </div>
                                </figure>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article class="singleMember clearfix">
                                <figure>
                                    <img src="img/team2.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="teamMember text-center">
                                    <a href="#"><h4 class="text-uppercase">BILLY CASTRO</h4></a>
                                    <h3>MANAGER</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing 
                                        elit, sed diam my nibh euismod tincidunt
                                    </p>
                                    <ul class="list-inline list-unstyled">
                                        <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-pinterest-p"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article class="singleMember clearfix">
                                <figure>
                                    <img src="img/team3.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="teamMember text-center">
                                    <a href="#"><h4 class="text-uppercase">DAVID SMITH</h4></a>
                                    <h3>MANAGER</h3>
                                    <p>
                                        Lorem ipsum dolor sit amet, consectetuer adipiscing 
                                        elit, sed diam my nibh euismod tincidunt
                                    </p>
                                    <ul class="list-inline list-unstyled">
                                        <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                        <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                        <li><a href="#"><span class="fa fa-pinterest-p"></span></a></li>
                                        <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    </ul>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </section>


            <!-- SECTION 5 " -->
            <section class="popular">
                <h4 class="text-uppercase text-center">new arrivals</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 7 "arrivals -->    
            <section class="arrivals">
                <div class="container">
                    <div id="owl-example" class="owl-carousel">
                        <article>
                            <div>
                                <figure>
                                    <img src="img/plash.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/eminence.png" alt="" class="img-responsive center-block"/> 
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/spa-body.png" alt="" class="img-responsive center-block"/> 
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/aveeno.png" alt="" class="img-responsive center-block"/> 
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/facial.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/towel.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/arctic.png" alt="" class="img-responsive center-block"/>
                                </figure>
                            </div>
                            <div class="carouselHover">
                                <a href="#">
                                    <h4>Green apple peel</h4>  
                                    <p>$ 125.00</p>
                                </a>
                                <a href="#"><span class="fa fa-refresh"></span></a>
                                <button>ADD TO CART</button>
                                <a href="#"><span class="fa fa-heart-o"></span></a>
                            </div>
                        </article>
                        <article>
                            <div>
                                <figure>
                                    <img src="img/vitamin.png" alt="" class="img-responsive center-block"/>
                                </figure>
                                <div class="carouselHover">
                                    <a href="#">
                                        <h4>Green apple peel</h4>  
                                        <p>$ 125.00</p>
                                    </a>
                                    <a href="#"><span class="fa fa-refresh"></span></a>
                                    <button>ADD TO CART</button>
                                    <a href="#"><span class="fa fa-heart-o"></span></a>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </section>

            <!-- SECTION 8 "shipping" -->
            <section class="shipping">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <article>
                                <span class="fa fa-truck"></span>
                                <a href="#"><h5>FREE SHIPPING</h5></a>
                                <p>Lorem ipsum dummy text here</p>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <span class="fa fa-check-square"></span>
                                <a href="#"><h5>MONEYBACK GUARANTEE</h5></a>
                                <p>Lorem ipsum dummy text here</p>
                            </article>
                        </div>
                        <div class="col-sm-4">
                            <article>
                                <span class="fa fa-headphones"></span>
                                <a href="#"><h5>ONLINE SUPPORT</h5></a>
                                <p>24/7 Lorem ipsum dummy support</p>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
        </main>
