<main>
            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    <h3 class="text-uppercase text-center">ABOUT US</h3>
                    
                </div>
            </section>

            <!-- SECTION 2 -->
            <section class="popular">
                <h4 class="text-uppercase text-center">about us</h4>
                <img src="<?php echo $this->baseUrl('/front/img/line.png');?>" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 3 " -->
            <section class="ourCompany">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <article>
                                <h4 class="text-uppercase">who we are?</h4> 
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipisicing 
                                    elit, sed do eiusmod tempor incididunt ut labore et 
                                    dolore magna aliqua. Ut enim ad minim veniam, quis 
                                    nostrud exercitation ullamco laboris nisi ut aliquip 
                                    ex ea commodo consequat enim ad minim veniam, 
                                    quis nostrud exercita.
                                </p>
                                <p>
                                    Excepteur sint occaecat cupidatat non proident, 
                                    sunt in culpa qui officia deserunt mollit anim id 
                                    est laborum. Sed ut perspiciatis unde omnis iste 
                                    natus error sit voluptatem accusantium 
                                </p>
                                <p>FOLLOW US:</p>
                                <ul class="list-inline list-unstyled">
                                    <li><a href="#"><span class="fa fa-facebook"></span></a></li>
                                    <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                    <li><a href="#"><span class="fa fa-pinterest-p"></span></a></li>
                                    <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                    <li><a href="#"><span class="fa fa-instagram"></span></a></li>
                                </ul>
                            </article>
                        </div>
                        <div class="col-md-6">
                            <article class="clearfix">
                                <figure>
                                    <img src="<?php echo $this->baseUrl('/front/img/shop.png');?>" alt="" class="img-responsive center-block"/>
                                </figure>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
        </main>
