<?php

$product = $this->product;

$this->headTitle('Product - ' . $product['product_name']);
?>

<!-- SECTION 4 " -->
            <section class="popular">
                <h4 class="text-uppercase text-center">Proizvodi koje koristimo</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 5 " -->
            <section class="ourTeam">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <article class="singleProduct clearfix">
                                <figure>
                                    <img src="<?php echo $this->productImgUrl($product);?>" alt="" class="img-responsive center-block"/>

                                    <div class="product text-center">
                                        <a href="#"><h4 class="text-uppercase"><?php echo $this->escape($product['product_name']); ?></h4></a>
                                        
                                        <p>
                                            <?php echo $this->escape($product['resume']); ?>
                                        </p>
                                        
                                    </div>
                                </figure>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
