<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?php echo $this->headTitle('Make up studio')->setSeparator(' | '); ?>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- @todo: fill with your company info or remove -->
        <?php echo $this->headMeta(); ?>
        <!-- General CSS -->


        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/bootstrap.css'); ?>">
        <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,600,600italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic,900,900italic,300italic' rel='stylesheet' type='text/css'>
        <link href="<?php echo $this->baseUrl('/front/css/owl.carousel.css'); ?>" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/owl.theme.css" rel="stylesheet'); ?>" type="text/css"/>
        <link href="<?php echo $this->baseUrl('/front/css/image-switcher.css'); ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="<?php echo $this->baseUrl('/front/css/main.css'); ?>">
        <link href="<?php echo $this->baseUrl('/front/css/responsive.css'); ?>" rel="stylesheet" type="text/css"/>




        <?php echo $this->headLink(); ?>
        <!-- Theme  CSS -->

        <?php echo $this->headStyle(); ?>

        <?php echo $this->headScript(); ?>
    </head>

    <!-- ======== @Region: body ======== -->
    <!-- HEADER -->
    <body>
        <header>
            <div class="container">
                <section class="headerTop clearfix">
                    <ul class="account list-inline text-right">
                        <li>
                            <p class="map"><a href="mailto:majasminkerica@gmail.com"><span class="fa fa-envelope"></span>&nbsp; majasminkerica@gmail.com</a></p>
                        </li>
                    </ul>
                </section>
            </div>
            <div class="line"></div>

            <!-- NAVIGATION -->
            <div class="container myNav">
                <nav class="navbar navbar-default navDrop">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="<?php echo $this->baseUrl('/'); ?>">
                                <img src="<?php echo $this->baseUrl('/front/img/logo.png'); ?>" alt="" class="img-responsive"/>
                            </a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                            <?php echo $this->topMenuHtml(); ?>
                        </div>
                    </div><!-- /.container-fluid -->
                </nav>
            </div>
        </header>
        <?php echo $this->layout()->content; ?>


        <!-- FOOTER -->
        <footer>
            <!-- SECTION 7 "socialnetworks" -->    
            <section class="newsletter">
                <div class="container">
                    <div class="row">
                            <article class="social">
                                <ul class="list-inline list-unstyled text-center">
                                    <li>
                                        <a href="https://www.facebook.com/majasminkerica011/" target="_blank"><span class="fa fa-facebook"></span></a>
                                    </li>
                                    <li>
                                        <a href="https://plus.google.com/u/2/?hl=sr" target="_blank"><span class="fa fa-google-plus"></span></a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/maja_sminkerica/" target="_blank"><span class="fa fa-instagram"></span></a>
                                    </li>
                                </ul>
                            </article>
                    </div>
                </div>
            </section>
            
            <!-- SECTION 8 "topmenu" -->
            <section>
                <div class="container">
                    <div class="row">
                            <?php echo $this->topMenuHtml(); ?>
                    </div>
                </div>
            </section>
            
            <!-- SECTION 9 "rights" -->
            <section class=" rights text-center">
                <p class="">Ovaj projekat je realizovan u okviru <a href="http://school.cubes.rs" target="_blank">CUBES SCHOOL</a>. Projekat realizovali: FRONTEND <a href="#">Tanja Nikolic</a> & <a href="#">Miroslav Ranisavljevic</a> BACKEND: <a href="https://rs.linkedin.com/in/aleksandra-petkovic-316b46116" target="_blank">Aleksandra Petkovic</a></p>
            </section>
        </footer>


        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h3 class="modal-title" id="myModalLabel">Insert main title</h3>
                    </div>
                    <div class="modal-body">
                        <h4>Insert second title here</h4>
                        <p>
                            Cras mattis consectetur purus sit amet fermentum. Cras 
                            justo odio, dapibus ac facilisis in, egestas eget quam. 
                            Morbi leo risus, porta ac consectetur ac, vestibulum at eros
                        </p>
                        <p>
                            Cras mattis consectetur purus sit amet fermentum. Cras 
                            justo odio, dapibus ac facilisis in, egestas eget quam. 
                            Morbi leo risus, porta ac consectetur ac, vestibulum at eros
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal end-->

        <script src="<?php echo $this->baseUrl('/front/js/jquery-3.0.0.min.js'); ?>" type="text/javascript"></script>
        <script>window.jQuery || document.write('<script src="<?php echo $this->baseUrl('/front/js/vendor/jquery-1.11.2.js'); ?>"><\/script>')</script>

        <script src="<?php echo $this->baseUrl('/front/js/vendor/bootstrap.min.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/front/js/owl.carousel.js" type="text/javascript'); ?>"></script>
        <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
        <script src="<?php echo $this->baseUrl('/front/resources/demos/external/jquery-mousewheel/jquery.mousewheel.js'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/front/js/validator.js" type="text/javascript'); ?>"></script>
        <script src="<?php echo $this->baseUrl('/front/js/main.js'); ?>"></script>

        <?php echo $this->inlineScript(); ?>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function (b, o, i, l, e, r) {
                b.GoogleAnalyticsObject = l;
                b[l] || (b[l] =
                        function () {
                            (b[l].q = b[l].q || []).push(arguments)
                        });
                b[l].l = +new Date;
                e = o.createElement(i);
                r = o.getElementsByTagName(i)[0];
                e.src = '//www.google-analytics.com/analytics.js';
                r.parentNode.insertBefore(e, r)
            }(window, document, 'script', 'ga'));
            ga('create', 'UA-XXXXX-X', 'auto');
            ga('send', 'pageview');
        </script>


        <!--Scripts -->

    </body>

</html>
