<?php
$this->headTitle('Products - New Product');

$form = $this->form;

$form->setElementDecorators(array('ViewHelper'));

?>


<div class="page-header">
    <h1>New Product</h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right">
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true); ?>" type="button" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i>Back to all products</a>
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    <input type="hidden" name="task" value="save">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>New Product</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="product">Product name</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('product_name')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => "enter product\'s name", 
                                    'id' => "name",
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('product_name')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('product_name')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>

                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Description</label>
                            <div class="col-md-4">  
                                <?php
                                echo $form->getElement('resume')->setAttribs(array(
                                    'class' => 'form-control',
                                    'id' => 'resume',
                                    'rows' => 12,
                                ));
                                ?>
                                
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('resume')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('resume')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                        
                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="product_photo">Photo</label>
                            <div class="col-md-4">  
                                <input type="file" name="product_photo" id="product_photo" class="form-control input-md">
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('product_photo')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('product_photo')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group ">
                            <label class="col-md-4 control-label" for="new_product_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a
                                    href="<?php echo $this->url(array('controller' => 'admin_products', 'action' => 'index'), 'default', true);?>"
                                    id="new_product_cancel" name="new_product_cancel" class="btn btn-default">Cancel</a>
                                
                                <button type="submit" name="new_product_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>

            </div>
        </div>
    </div>
</div>
