<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
?>

<main>

            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    <h3 class="text-uppercase text-center">ABOUT US</h3>
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#"> Shop</a>
                        </li>
                        <li>Grid View</li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 2 -->
            <section class="popular">
                <h4 class="text-uppercase text-center">about our company</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 3 "contactForm" -->
            <section class="contactForm">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <article>
                                <h4 class="text-uppercase">contact form</h4>
                                <div class="inputForm">
                                    <form class="html_form" data-toggle="validator" role="form">
                                        <div class="form-group">
                                            <label for="inputName" class="control-label sr-only">Ime i prezime</label>
                                            <input type="text" pattern="^[_A-z\s]{1,}$" data-minlength="4" class="form-control" id="inputName" data-error="Enter your name" placeholder="Name&ast;" required>
                                        <div class="help-block with-errors"></div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputEmail" class="control-label sr-only">Email</label>
                                            <input type="email" class="form-control" id="inputEmail" placeholder="E-mail&ast;" data-error="Email address is not valid" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputSubject" class="control-label sr-only">Subject</label>
                                            <input type="text"  class="form-control" id="inputSubject" placeholder="Subject">
                                        </div>
                                        <div class="form-group">
                                            <textarea class="form-control" name="comment" rows="4" placeholder="Message"></textarea>
                                        </div>
                                        <div class="form-group">
                                                <button type="submit" class="btn btn-primary">SEND MESSAGE</button>
                                        </div>
                                    </form>
                                </div>
                            </article>
                        </div>
                        <div class="col-md-6 addrCon">
                            <h4 class="text-uppercase">contact address</h4>
                            <article class="contAddress">
                                <div class="contact">
                                    <ul class="list-unstyled">
                                        <li>
                                            <p class="map"><span class="fa fa-map-marker"></span>&nbsp; 123 West Street, Melbourne Victoria 3000 Australia</p>
                                        </li>
                                        <li>
                                            <p class="map"><span class="fa fa-phone"></span>&nbsp; Phone : +061012345678 <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Fax : +006101234567</p>
                                        </li>
                                        <li>
                                            <p class="map"><span class="fa fa-envelope"></span>&nbsp; 
                                                <a href="mailto:Contact@yourename.com">Contact@yourename.com</a> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                                                <a href="mailto:Support@yourname.com">Support@yourname.com</a>
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </article>
                        </div>
                    </div>
                </div>
            </section>

            <!-- SECTION 4 "gMaps" -->
            <section class="gMaps">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d48371.24948273937!2d-73.93035534680745!3d40.735556443668976!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1469789242670" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </section>
        </main>