<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
?>
<main>
    <?php echo $this->topPhoto(); ?>

    <div class="gridView">
        <h3 class="text-uppercase text-center"><?php echo $this->sitemapPage['title']; ?></h3>
    </div>
</section>

<!-- SECTION 2 -->
<section class="popular">
    <h4 class="text-uppercase text-center">Kontaktirajte nas</h4>
    <img src="img/line.png" alt="" class="img-responsive center-block"/>
</section>

<!-- SECTION 3 "contactForm" -->
<section class="contactForm">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <article>
                    <h4 class="text-uppercase">contact form</h4>
                    <div class="inputForm">
                        <form class="html_form" data-toggle="validator" role="form">
                            <div class="form-group">


                                <?php
                                echo $form->getElement('name')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'Name*',
                                    'id' => 'name',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 3 max 255 characters</span>  

                                <div class="help-block with-errors"></div>
                                <?php if ($form->getElement('name')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>

                            <div class="form-group">
                                <?php
                                echo $form->getElement('email')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'E-mail*',
                                    'id' => 'email',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 3 max 255 characters</span>  

                                <div class="help-block with-errors">
                                    <?php if ($form->getElement('email')->hasErrors()) { ?>
                                        <div class="has-error">
                                            <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>

                            </div>

                            <div class="form-group">
                                <?php
                                echo $form->getElement('message')->setAttribs(array(
                                    'class' => 'form-control',
                                    'placeholder' => 'Message*',
                                    'id' => 'message',
                                    'rows' => 5
                                ));
                                ?>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">SEND MESSAGE</button>
                            </div>
                        </form>
                    </div>
                </article>
            </div>
            <?php echo $sitemapPage["body"]; ?>

        </div>
    </div>
</section>

<!-- SECTION 4 "gMaps" -->
<section class="gMaps">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d181139.35623527557!2d20.282170365642536!3d44.81540286862992!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475a7aa3d7b53fbd%3A0x1db8645cf2177ee4!2sBelgrade%2C+Serbia!5e0!3m2!1sen!2srs!4v1473432024838" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>            </section>
</main>