<?php
$sitemapPage = $this->sitemapPage;
$this->headTitle($sitemapPage['title']);
?>
<main>
            <!-- SECTION 1 "frid" -->
            <section class="frid clearfix">
                <figure>
                    <img src="<?php echo $this->baseUrl('/front/img/hot-stone.jpg');?>" alt="" class="img-responsive"/>
                </figure>
                <div class="gridView">
                    
                    <ul class="breadcrumb list-inline text-uppercase text-center">
                        <li>
                            <a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
                        </li>
                    </ul>
                </div>
            </section>

            <!-- SECTION 2 -->
            <section class="popular">
                <h4 class="text-uppercase text-center">about our company</h4>
                <img src="img/line.png" alt="" class="img-responsive center-block"/>
            </section>

            <!-- SECTION 3 "contactForm" -->
            <section class="contactForm">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <article>
                                <h4 class="text-uppercase">contact form</h4>
                                <div class="inputForm">
                                    <form class="html_form" data-toggle="validator" role="form">
                                        <div class="form-group">
                                            <label for="inputName" class="control-label sr-only">Ime i prezime</label>
                                            <input type="text" pattern="^[_A-z\s]{1,}$" data-minlength="4" class="form-control" id="inputName" data-error="Enter your name" placeholder="Name&ast;" required>
                                        <div class="help-block with-errors"></div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputEmail" class="control-label sr-only">Email</label>
                                            <input type="email" class="form-control" id="inputEmail" placeholder="E-mail&ast;" data-error="Email address is not valid" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputSubject" class="control-label sr-only">Subject</label>
                                            <input type="text"  class="form-control" id="inputSubject" placeholder="Subject">
                                        </div>
                                        <div class="form-group">
                                            <textarea class="form-control" name="comment" rows="4" placeholder="Message"></textarea>
                                        </div>
                                        <div class="form-group">
                                                <button type="submit" class="btn btn-primary">SEND MESSAGE</button>
                                        </div>
                                    </form>
                                </div>
                            </article>
                        </div>
                        <?php echo $sitemapPage["body"];?>

                    </div>
                </div>
            </section>

            <!-- SECTION 4 "gMaps" -->
            <section class="gMaps">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d181139.35623527557!2d20.282170365642536!3d44.81540286862992!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475a7aa3d7b53fbd%3A0x1db8645cf2177ee4!2sBelgrade%2C+Serbia!5e0!3m2!1sen!2srs!4v1473432024838" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>            </section>
        </main>